### ISSUE TITLE
AR model

### ISSUE THREAD

**Issue by tongtong-design** [BoXun97/DS4D_GroupProject#5]
Is it better to use bar graphs to show the proportion of substantive measures or to use pie graphs to show them? Are bar graphs and pie graphs displayed on one card? How many keywords should be selected to make a word cloud?

**Comment by Xhuiii** [comment]
I think it might be more clear to use pie graphs because users can browse the 3D model by rotating and zooming in. When looking at the screen, the pie graph is more concise and more readable. Besides, considering the size of the page and user experience of the AR app, we can display the two models separately and use only the top 5 to 10 keywords to create a word cloud.
